'use client'

import { useState } from 'react'
import { ArrowRight, BookOpen, Clock3, Camera, Library, MapPin, Menu, MessageCircle, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

type Achiever = {
  id: string
  student_name: string
  photo_url: string | null
  job_title: string
  organization: string
  department: string | null
  exam_name: string
  selection_year: number
  preparation_duration: string | null
  testimonial: string | null
  success_story: string | null
}

export default function LibraryHome({ achievers, seatCount, monthlyFee }: { achievers: Achiever[]; seatCount: number; monthlyFee: number | null }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeStory, setActiveStory] = useState(0)
  const visibleAchievers = achievers.slice(activeStory, activeStory + 3)

  return (
    <main className="site-shell">
      <header className="site-header">
        <a href="#home" className="brand" aria-label="The Peaceful Pages Library home"><span className="brand-mark"><BookOpen /></span><span><strong>The Peaceful Pages</strong><small>LIBRARY</small></span></a>
        <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button>
        <nav className={menuOpen ? 'main-nav open' : 'main-nav'}><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#facilities" onClick={() => setMenuOpen(false)}>Facilities</a><a href="#success-stories" onClick={() => setMenuOpen(false)}>Success Stories</a><a href="#seats" onClick={() => setMenuOpen(false)}>Study Seats</a><a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a><a className="nav-login" href="/auth/login">Student Login <ArrowRight /></a></nav>
      </header>

      <section className="hero" id="home"><div className="hero-copy"><div className="eyebrow"><Sparkles /> A calmer way to study</div><h1>Your space to<br /><em>read, relax,</em> and rise.</h1><p>Find your focus in a thoughtfully designed library made for ambitious minds. Quiet corners, reliable Wi-Fi, and a seat that feels like yours.</p><div className="hero-actions"><a href="#seats" className="primary-button">Book a study seat <ArrowRight /></a><a href="#about" className="text-button">Discover the library <ArrowRight /></a></div><div className="hero-proof"><div className="avatar-stack"><span>AS</span><span>RK</span><span>PM</span><span>+</span></div><span><strong>500+ focused minds</strong><br />call Peaceful Pages home</span></div></div><div className="hero-visual" aria-label="Library reading room"><div className="hero-image"><div className="sun-glow" /><div className="window-line one" /><div className="window-line two" /><div className="bookshelf"><i /><i /><i /><i /><i /><i /></div><div className="reading-table"><span /><span /><span /></div><div className="plant"><b /><i /><i /><i /></div></div><div className="floating-note"><span className="status-dot" /><div><strong>Open today</strong><small>06:00 AM — 11:00 PM</small></div><Clock3 /></div><div className="hero-caption"><span>01</span><div><strong>A quiet place to do your best work.</strong><small>Designed for deep focus.</small></div></div></div></section>
      <section className="stats-strip" id="about"><div><strong>6 AM — 11 PM</strong><span>Open every day</span></div><div><strong>{seatCount}</strong><span>Numbered study seats</span></div><div><strong>100 Mbps</strong><span>Fast, stable Wi-Fi</span></div><div><strong>4.9 / 5</strong><span>Member experience</span></div></section>
      <section className="section facilities" id="facilities"><div className="section-heading"><div><div className="eyebrow">Everything you need</div><h2>Made for your<br /><em>best hours.</em></h2></div><p>Every detail is considered to help you settle in, stay present, and make progress on the work that matters to you.</p></div><div className="feature-grid"><article><span className="feature-icon"><Library /></span><h3>A seat that fits your rhythm</h3><p>Reserve your preferred spot before you arrive. From window desks to quiet corners, find your kind of focus.</p><a href="#seats">Explore seats <ArrowRight /></a></article><article><span className="feature-icon"><ShieldCheck /></span><h3>Peace, protected</h3><p>Thoughtful rules, clean spaces, and a community that respects the quiet make concentration feel effortless.</p><a href="#contact">Our promise <ArrowRight /></a></article><article><span className="feature-icon"><Users /></span><h3>A community of doers</h3><p>Meet students and professionals who show up with intention. You do not have to study alone.</p><a href="#pricing">Become a member <ArrowRight /></a></article></div></section>

      <section className="success-section" id="success-stories"><div className="section-heading"><div><div className="eyebrow">From our library to government service</div><h2>Quiet work.<br /><em>Big futures.</em></h2></div><p>Celebrating the students who turned their preparation into success.</p></div>{visibleAchievers.length ? <><div className="success-grid">{visibleAchievers.map((achiever) => <article className="success-card" key={achiever.id}>{achiever.photo_url ? <img src={achiever.photo_url} alt={`Portrait of ${achiever.student_name}`} loading="lazy" /> : <div className="success-photo-fallback" aria-hidden="true"><BookOpen /></div>}<div className="success-card-body"><span className="success-year">Selected {achiever.selection_year}</span><h3>{achiever.student_name}</h3><strong>{achiever.job_title}</strong><span>{achiever.organization}{achiever.department ? ` · ${achiever.department}` : ''}</span><small>{achiever.exam_name}{achiever.preparation_duration ? ` · ${achiever.preparation_duration} preparation` : ''}</small>{achiever.testimonial && <blockquote>“{achiever.testimonial}”</blockquote>}{achiever.success_story && <details><summary>View Success Story</summary><p>{achiever.success_story}</p></details>}</div></article>)}</div><div className="success-controls"><button disabled={activeStory === 0} onClick={() => setActiveStory(Math.max(0, activeStory - 1))} aria-label="Previous success stories">←</button><span>{activeStory + 1} / {Math.max(1, achievers.length - 2)}</span><button disabled={activeStory >= achievers.length - 3} onClick={() => setActiveStory(Math.min(Math.max(0, achievers.length - 3), activeStory + 1))} aria-label="Next success stories">→</button></div></> : <div className="success-empty">Our success stories are coming soon.</div>}<div className="success-cta"><div><strong>Your Success Story Could Be Next.</strong><span>Build your next chapter in a space made for focus.</span></div><a href="/auth/sign-up" className="primary-button">Join The Peaceful Pages <ArrowRight /></a></div></section>

      <section className="booking-section" id="seats"><div className="booking-intro"><div className="eyebrow">Plan your focus</div><h2>Choose your<br /><em>quiet corner.</em></h2><p>Members choose a date, time slot, and available seat from their dashboard. Availability updates as bookings change.</p><div className="legend"><span>{seatCount} numbered seats in the library</span></div></div><div className="booking-card"><div className="booking-top"><div><strong>Numbered study seats</strong><small>Choose a seat after signing in</small></div><span className="status-pill active">{seatCount} seats</span></div><div className="seat-map inventory-seat-map">{Array.from({ length: seatCount }, (_, index) => index + 1).map((seat) => <span className="seat inventory-seat" key={seat}>{seat}</span>)}</div><div className="booking-bottom"><div><small>VISIT BOOKING</small><strong>Choose your own time slot <span>·</span> free booking</strong></div><a href="/auth/sign-up" className="primary-button">Join to book <ArrowRight /></a></div></div></section>
      <section className="section pricing" id="pricing"><div className="section-heading"><div><div className="eyebrow">Simple membership</div><h2>Find your<br /><em>flow.</em></h2></div><p>Membership fees are managed by the library. All bookings are free and require admin verification of the current payment.</p></div><div className="plans"><article className="plan"><span className="plan-name">One-time registration</span><strong>₹100</strong><span className="plan-detail">Paid once after student registration</span><span className="plan-check">Verified manually by the library</span></article><article className="plan featured"><span className="popular">Monthly membership</span><span className="plan-name">Monthly library fee</span><strong>{monthlyFee ? '₹' + monthlyFee : 'Ask the library'}</strong><span className="plan-detail">Per billing month</span><span className="plan-check">Amount set by the administrator</span></article><article className="plan"><span className="plan-name">Seat bookings</span><strong>₹0</strong><span className="plan-detail">For each visit</span><span className="plan-check">Book from your student dashboard</span></article></div></section>
      <section className="cta-section" id="contact"><div><div className="eyebrow">Your next chapter starts here</div><h2>Make room for<br /><em>what matters.</em></h2></div><div><p>Ready to find your place? Come see why focused people choose Peaceful Pages.</p><a className="light-button" href="/auth/sign-up">Register as a student <ArrowRight /></a></div></section><footer><a href="#home" className="brand"><span className="brand-mark"><BookOpen /></span><span><strong>The Peaceful Pages</strong><small>LIBRARY</small></span></a><span className="footer-copy">Read. Relax. Rise.</span><div className="socials"><a href="#contact" aria-label="WhatsApp"><MessageCircle /></a><a href="#contact" aria-label="Instagram"><Camera /></a><a href="#contact" aria-label="Google Maps"><MapPin /></a></div></footer>
    </main>
  )
}

export type { Achiever }
